# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

target 'ZoomSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZoomSample
  pod 'SwiftGen'
  pod 'SwiftLint'
  pod 'ZoomSDK', :git => 'https://github.com/Yoshiatsu-Irei/ZoomSDK.git'
  # pod 'ZoomSDK', :git => 'https://github.com/pavelsmelovsky/ZoomSDK.git'

end
